[General]
cmdenv-autoflush = true

##########################################################
#            Simulation parameters                       #
##########################################################
debug-on-errors = false
print-undisposed = false

sim-time-limit = 1200s

**.sctp.**.scalar-recording = false
**.sctp.**.vector-recording = false
**.routingRecorder.enabled = false

*.playgroundSizeX = 20000m
*.playgroundSizeY = 20000m
*.playgroundSizeZ = 50m


##########################################################
#                      Mobility                          #
##########################################################
*.ue[*].mobility.typename = "VeinsInetMobility"
*.mmecHost[*].mobility.typename = "VeinsInetMobility"
*.mecHost[*].mobility.typename = "VeinsInetMobility"


##########################################################
#                       APPS                            #
##########################################################
*.mecHost*.udpHostSink.localPort = 1000
*.mmecHost*.udpHostSink.localPort = 1000

*.ue*.udpUeApp.localPort = 1010
*.ue*.udpUeApp.destPort = 1000
*.ue*.udpUeApp.sendInterval = 1s
*.ue*.udpUeApp.messageLength = 1000B
##########################################################
#                       WLAN                            #
##########################################################
*.ue*.numWlanInterfaces = 1
*.ue*.ipv4.configurator.interfaces =  "wlan lo0"

*.mmecHost*.numWlanInterfaces = 1
*.mmecHost*.ipv4.configurator.interfaces =  "wlan lo0"

*.mecHost*.numWlanInterfaces = 1
*.mecHost*.ipv4.configurator.interfaces =  "wlan lo0"

**.wlan*.radio.antenna.typename = "IsotropicAntenna"
# This antenna model describes the theoretical point source which radiates the
# same intensity of radiation in all directions.

# no need of extra mobility
**.wlan*.radio.antenna.mobility.typename = ""
**.wlan*.radio.antenna.mobilityModule = "^.^.^.mobility"

**.wlan*.mgmt.typename = "Ieee80211MgmtAdhoc"
**.wlan*.agent.typename = ""


##########################################################
#                Orchestrator Setting                    #
##########################################################
#*.orchestrator.mecHostList = "mecHost1, mecHost2, mecHost3"
#*.orchestrator.algorithmName="ClosestFit"
#*.orchestrator.algorithmName="ABC"
*.orchestrator.wIFIDistance = 1000
*.orchestrator.updateInterval =1s
*.orchestrator.spInterval = 1s

**.mecHost*.requestProcessTime = 1s
**.mmecHost[*].requestProcessTime = 1s

##########################################################
#                  background noise                      #
##########################################################

*.radioMedium.backgroundNoise.typename = "IsotropicScalarBackgroundNoise"
*.radioMedium.backgroundNoise.power = -100 dBm#city noise

*.radioMedium.pathLoss.alpha = 2.2 


# ARP
#**.mecHost*.ipv4.arp.typename = "GlobalArp"
#**.mmecHost[*].ipv4.arp.typename = "GlobalArp"
#**.ue[*].ipv4.arp.typename = "GlobalArp"

**.wlan[*].opMode = "g(erp)"
**.wlan[*].radio.transmitter.power = 10mW



##########################################################
#                    Plcaement Polocy                    #
##########################################################
*.orchestrator.algorithmName = "BestHost"


**.mecHost*.maxRam = 1GB
**.mecHost*.maxDisk = 50GB
**.mecHost*.maxCpuSpeed = 1500

**.mmecHost[*].maxRam = 1GB
**.mmecHost[*].maxDisk = 50GB
**.mmecHost[*].maxCpuSpeed = 1500

**.mecHost*.resource_used_pro_up = 0.95
**.mecHost*.resource_used_pro_low = 0.6

**.mecHost[*].resource_used_pro_up = 0.95
**.mmecHost[*].resource_used_pro_low = 0.6

[Config fifty_static_zero_mobile]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.fiftyStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue"
*.veinsManager.moduleName = "car=ue "
*.veinsManager.launchConfig = xmldoc("gridMapFourKm_zero.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs'"

[Config hundred_static_zero_mobile]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.hundredStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue"
*.veinsManager.moduleName = "car=ue "
*.veinsManager.launchConfig = xmldoc("gridMapFourKm_zero.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs'"

[Config zero_static_half_mobile]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.noStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue *=mobiedgesim.nodes.mobileNodes.mmecHost.MmecHost"
*.veinsManager.moduleName = "car=ue *=mmecHost"
*.veinsManager.launchConfig = xmldoc("gridMapFourKm_half.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs' *='i=device/server2;is=vs'"

[Config fifty_static_half_mobile]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.fiftyStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue *=mobiedgesim.nodes.mobileNodes.mmecHost.MmecHost"
*.veinsManager.moduleName = "car=ue *=mmecHost"
*.veinsManager.launchConfig = xmldoc("gridMapFourKm_half.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs' *='i=device/server2;is=vs'"

[Config hundred_static_half_mobile]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.hundredStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue *=mobiedgesim.nodes.mobileNodes.mmecHost.MmecHost"
*.veinsManager.moduleName = "car=ue *=mmecHost"
*.veinsManager.launchConfig = xmldoc("gridMapFourKm_half.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs' *='i=device/server2;is=vs'"

[Config zero_static_total_mobile]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.noStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue *=mobiedgesim.nodes.mobileNodes.mmecHost.MmecHost"
*.veinsManager.moduleName = "car=ue *=mmecHost"
*.veinsManager.launchConfig = xmldoc("gridMapFourKm.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs' *='i=device/server2;is=vs'"

[Config fifty_static_total_mobile]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.fiftyStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue *=mobiedgesim.nodes.mobileNodes.mmecHost.MmecHost"
*.veinsManager.moduleName = "car=ue *=mmecHost"
*.veinsManager.launchConfig = xmldoc("gridMapFourKm.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs' *='i=device/server2;is=vs'"

[Config hundred_static_total_mobile]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.hundredStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue *=mobiedgesim.nodes.mobileNodes.mmecHost.MmecHost"
*.veinsManager.moduleName = "car=ue *=mmecHost"
*.veinsManager.launchConfig = xmldoc("gridMapFourKm.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs' *='i=device/server2;is=vs'"


[Config fifty_static_zero_mobile_low_resource]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.fiftyStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue"
*.veinsManager.moduleName = "car=ue "
*.veinsManager.launchConfig = xmldoc("gridMapFourKm_zero.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs'"

**.resource_used_pro = 0.9


[Config hundred_static_zero_mobile_low_resource]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.hundredStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue"
*.veinsManager.moduleName = "car=ue "
*.veinsManager.launchConfig = xmldoc("gridMapFourKm_zero.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs'"

**.resource_used_pro = 0.9

[Config zero_static_half_mobile_low_resource]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.noStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue *=mobiedgesim.nodes.mobileNodes.mmecHost.MmecHost"
*.veinsManager.moduleName = "car=ue *=mmecHost"
*.veinsManager.launchConfig = xmldoc("gridMapFourKm_half.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs' *='i=device/server2;is=vs'"

**.resource_used_pro = 0.9

[Config fifty_static_half_mobile_low_resource]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.fiftyStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue *=mobiedgesim.nodes.mobileNodes.mmecHost.MmecHost"
*.veinsManager.moduleName = "car=ue *=mmecHost"
*.veinsManager.launchConfig = xmldoc("gridMapFourKm_half.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs' *='i=device/server2;is=vs'"

**.resource_used_pro = 0.9

[Config hundred_static_half_mobile_low_resource]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.hundredStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue *=mobiedgesim.nodes.mobileNodes.mmecHost.MmecHost"
*.veinsManager.moduleName = "car=ue *=mmecHost"
*.veinsManager.launchConfig = xmldoc("gridMapFourKm_half.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs' *='i=device/server2;is=vs'"

**.resource_used_pro = 0.9


[Config zero_static_total_mobile_low_resource]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.noStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue *=mobiedgesim.nodes.mobileNodes.mmecHost.MmecHost"
*.veinsManager.moduleName = "car=ue *=mmecHost"
*.veinsManager.launchConfig = xmldoc("gridMapFourKm.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs' *='i=device/server2;is=vs'"

**.resource_used_pro = 0.9

[Config fifty_static_total_mobile_low_resource]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.fiftyStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue *=mobiedgesim.nodes.mobileNodes.mmecHost.MmecHost"
*.veinsManager.moduleName = "car=ue *=mmecHost"
*.veinsManager.launchConfig = xmldoc("gridMapFourKm.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs' *='i=device/server2;is=vs'"

**.resource_used_pro = 0.9


[Config hundred_static_total_mobile_low_resource]
network = mobiedgesim.simulations.SimpleNet.Four_Km_GridMap.hundredStatic
##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
#*.veinsManager.host = "sumo"       # traci-launchd on different host/container
*.veinsManager.moduleType = "car=mobiedgesim.nodes.mobileNodes.ue.Ue *=mobiedgesim.nodes.mobileNodes.mmecHost.MmecHost"
*.veinsManager.moduleName = "car=ue *=mmecHost"
*.veinsManager.launchConfig = xmldoc("gridMapFourKm.launchd.xml")
*.veinsManager.updateInterval = 1s
*.veinsManager.moduleDisplayString= "car='i=device/pocketpc;is=vs' *='i=device/server2;is=vs'"

**.resource_used_pro = 0.9

