[General]
cmdenv-autoflush = true

##########################################################
#            Simulation parameters                       #
##########################################################
debug-on-errors = false
print-undisposed = false

sim-time-limit = 1200s

**.sctp.**.scalar-recording = false
**.sctp.**.vector-recording = false
**.routingRecorder.enabled = false


##########################################################
#                      Mobility                          #
##########################################################
*.ue[*].mobility.typename = "VeinsInetMobility"
*.mmecHost[*].mobility.typename = "VeinsInetMobility"
*.mecHost[*].mobility.typename = "VeinsInetMobility"


##########################################################
#                       APPS                            #
##########################################################
*.mecHost*.udpHostSink.localPort = 1000
*.mmecHost*.udpHostSink.localPort = 1000

*.ue*.udpUeApp.localPort = 1010
*.ue*.udpUeApp.destPort = 1000
*.ue*.udpUeApp.sendInterval = 1s
*.ue*.udpUeApp.messageLength = 1000B
##########################################################
#                       WLAN                            #
##########################################################
*.ue*.numWlanInterfaces = 1
*.ue*.ipv4.configurator.interfaces =  "wlan lo0"

*.mmecHost*.numWlanInterfaces = 1
*.mmecHost*.ipv4.configurator.interfaces =  "wlan lo0"

*.mecHost*.numWlanInterfaces = 1
*.mecHost*.ipv4.configurator.interfaces =  "wlan lo0"

**.wlan*.radio.antenna.typename = "IsotropicAntenna"
# This antenna model describes the theoretical point source which radiates the
# same intensity of radiation in all directions.

# no need of extra mobility
**.wlan*.radio.antenna.mobility.typename = ""
**.wlan*.radio.antenna.mobilityModule = "^.^.^.mobility"

**.wlan*.mgmt.typename = "Ieee80211MgmtAdhoc"
**.wlan*.agent.typename = ""


##########################################################
#                Orchestrator Setting                    #
##########################################################
#*.orchestrator.mecHostList = "mecHost1, mecHost2, mecHost3"
#*.orchestrator.algorithmName="ClosestFit"
#*.orchestrator.algorithmName="ABC"
*.orchestrator.wIFIDistance = 1000
*.orchestrator.updateInterval =1s
*.orchestrator.spInterval = 1s

**.mecHost*.requestProcessTime = 1s
**.mmecHost[*].requestProcessTime = 1s

##########################################################
#                  background noise                      #
##########################################################

*.radioMedium.backgroundNoise.typename = "IsotropicScalarBackgroundNoise"
*.radioMedium.backgroundNoise.power = -100 dBm#city noise

*.radioMedium.pathLoss.alpha = 2.2 


# ARP
#**.mecHost*.ipv4.arp.typename = "GlobalArp"
#**.mmecHost[*].ipv4.arp.typename = "GlobalArp"
#**.ue[*].ipv4.arp.typename = "GlobalArp"

**.wlan[*].opMode = "g(erp)"
**.wlan[*].radio.transmitter.power = 10mW



##########################################################
#                    Plcaement Polocy                    #
##########################################################
*.orchestrator.algorithmName = "BestHost"


**.mecHost*.maxRam = 1GB
**.mecHost*.maxDisk = 50GB
**.mecHost*.maxCpuSpeed = 1500

**.mmecHost[*].maxRam = 1GB
**.mmecHost[*].maxDisk = 50GB
**.mmecHost[*].maxCpuSpeed = 1500

**.mecHost*.resource_used_pro_up = 0.95
**.mecHost*.resource_used_pro_low = 0.6

**.mecHost[*].resource_used_pro_up = 0.95
**.mmecHost[*].resource_used_pro_low = 0.6


*.playgroundSizeX = 100m
*.playgroundSizeY = 100m
*.playgroundSizeZ = 10m
[Config_two]
network = mobiedgesim.simulations.LatencyCompare.TStatic
[config_four]
network = mobiedgesim.simulations.LatencyCompare.FStatic
[config_eight]
network = mobiedgesim.simulations.LatencyCompare.EStatic

